### ISSUE TITLE
possible to disable remote config polling?

### ISSUE THREAD

**Issue by msaah-benchling** [DataDog/dd-trace-cpp#124]
hi, I'm testing out an upgrade of istio to the latest 1.22.0 version, which includes a version of envoy that uses the latest version of this library `0.2.0`.

we use the DD tracing integration in envoy that this library implements, but we have remote configuration disabled at the DD agent. this leads (I think) to an error in the envoy logs that looks like this:
```
2024-05-24T19:05:18.518647Z     error   envoy tracing external/envoy/source/extensions/tracers/datadog/logger.cc:23     Unexpected Remote Configuration status 503 with body (if any, starts on next line):
upstream connect error or disconnect/reset before headers. reset reason: connection termination thread=21
```

given that we don't want to use remote configuration, I'm wondering if it's possible to disable the polling entirely. I see the configuration exposes `DD_REMOTE_CONFIG_POLL_INTERVAL_SECONDS`, but it looks it [must be a positive value.](https://github.com/DataDog/dd-trace-cpp/blob/b5539307e5fa69767835a1bdb691eeefa60f7a45/src/datadog/datadog_agent_config.cpp#L117-L120)

am I missing anything here? ultimately I'd just like to not have this error being thrown constantly, so as a fallback perhaps I can just set the poll interval to a very long value, though that seems a bit sloppy.

let me know if you need any more context. thanks!

**Comment by dmehala** [comment]
Use `DD_INSTRUMENTATION_TELEMETRY_ENABLED`. More info on [the public documentation](https://docs.datadoghq.com/tracing/trace_collection/library_config/cpp/).

**Comment by msaah-benchling** [comment]
@dmehala a ha, thank you! couldn't find that page.
