### ISSUE TITLE
about thread safe

### ISSUE THREAD

**Issue by nqf** [DataDog/dd-trace-cpp#129]
Is this thread safe ？
```
int main() {
  datadog::tracing::Tracer trace;

  std::thread([&] {
  auto maybe_span = trace.extract_or_create_span(reader, config);
  });
  std::thread([&] {
  auto maybe_span = trace.extract_or_create_span(reader, config);
  });
sleep（100）；
}
```

**Comment by dgoffredo** [comment]
To be pedantic, if and only if the `reader` is thread safe.

The `Tracer` member functions `create_span`, `extract_span`, and `extract_or_create_span`, all instantiate a new `TraceSegment` and do not modify the invoked `Tracer`.

Those member functions could have been labeled `const`, but I left them non-`const` for possible future need. If such a need were to arrive, the maintainers would have to think about threading.

Here's an experimental [commit][1] that actually does make them `const`. All of the tests still pass.

Multiple new traces can be created from a single `Tracer` instance concurrently from multiple threads. It is thread safe.

See https://github.com/DataDog/dd-trace-cpp/issues/44 for a (contrived) scenario that is _not_ thread safe, but that is unrelated to your example.

[1]: https://github.com/dgoffredo/dd-trace-cpp/commit/827bad31a44bb15e320ae396a87cb0025e6972b5
