### ISSUE TITLE
404 Errors ( Unexpected telemetry response ) from Datadog Trace

### ISSUE THREAD

**Issue by koizumi7010** [DataDog/dd-trace-cpp#164]
Hello,
Recently, I updated Istio from version 1.20.8 to 1.21.6. Immediately after the update, the following errors have been occurring intermittently in the envoy tracing scope for every istio-proxy container:

```
[source/extensions/tracers/datadog/logger.cc:23] Unexpected Remote Configuration status 503 with body (if any, starts on next line):
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

```
[source/extensions/tracers/datadog/logger.cc:23] Unexpected telemetry response status 404 with body (if any, starts on next line):
404 page not found
```

I was able to resolve the first error by referring to [this Issue](https://github.com/istio/istio/issues/51430) and setting `DD_REMOTE_CONFIGURATION_ENABLED = "false"` in the IstioOperator YAML template file. 

However, I haven't been able to solve the second error yet.
And, I am not familiar with C++, but I found code blocks that seems to involve the error log.
https://github.com/DataDog/dd-trace-cpp/blob/main/src/datadog/datadog_agent.cpp#L176-L190

If anyone understands the cause of this error and knows how to resolve it, I would greatly appreciate your help.

**Comment by dmehala** [comment]
Hi @koizumi7010 

We collect telemetry to get more insight on the tracer and its usage. This feature can be disabled with `DD_INSTRUMENTATION_TELEMETRY_ENABLED=false`.

[Learn more on all the configurations we support.](https://docs.datadoghq.com/tracing/trace_collection/library_config/cpp/)

Let me know if that solve your issue :)

**Comment by koizumi7010** [comment]
@dmehala 
Thanks for the reply!
Setting `DD_INSTRUMENTATION_TELEMETRY_ENABLED = 'false'` in IstioOperator YAML template file eliminated the error :) 👍🏼
