### ISSUE TITLE
[question] encoding?  utf-8?

### ISSUE THREAD

**Issue by kristjanvalur** [DataDog/dd-trace-cpp#173]
I assume that char strings (names, tags, error messages, etc) sent to the agent are assumed to be UTF-8 encoded.  But since this is not mentioned anywhere I just want to get it confirmed.

Cheers!

**Comment by dmehala** [comment]
Hey @kristjanvalur 

Well as you may know, character encoding is a complex topic and even more in C++. The library heavily use `std::string` and works relatively well with UTF-8 if I recall correctly. Thus, It is fair to _assume_ the library handles UTF-8 encoding. On the agent, they fully support UTF-8.

**Comment by kristjanvalur** [comment]
Yes, I'm assuming the std::strings are just passed as they are to whatever payload (json?) is being sent to the agent. My question is, will the agent be expecting such strings to be utf 8?
In my integration I need to convert some of my internal strings from a widechar representation before passing them to the library. They may well be outside the ASCII range. The question is, can I safely encode them as utf8 for the library and will they be correctly understood by the agent and the DD visualisation tools?

**Comment by kristjanvalur** [comment]
Cool, just wanted it confirmed, might be worth adding in the "Span" or "SpanConfig" api docs.  Cheers!
