### ISSUE TITLE
Support Windows bazel builds

### ISSUE THREAD

**Issue by dgoffredo** [DataDog/dd-trace-cpp#84]
Envoy supports Windows, but without Datadog tracing.

If we can get dd-trace-cpp to build and test on Windows via bazel, then Envoy Windows builds could use the Datadog tracer.

See https://github.com/envoyproxy/envoy/issues/31649.

**Comment by sujeets-toast** [comment]
Hi Any update on this issue?

**Comment by dgoffredo** [comment]
> Hi Any update on this issue?

See <https://github.com/envoyproxy/envoy/issues/31649#issuecomment-1883033099>.

**Comment by dmehala** [comment]
Done in #119
