### ISSUE TITLE
`DD_TAGS` space separation

### ISSUE THREAD

**Issue by dmehala** [DataDog/dd-trace-cpp#88]
# Description

During my attempt to use `nginx-datadog` instead of the legacy nginx-opentracing module in system-tests. I found out `dd-trace-cpp` was crashing because of [this odd DD_TAGS expression](https://github.com/DataDog/system-tests/blob/47cdfce7fd9911f2828870fd69ae13db45da87fb/utils/build/docker/set-system-tests-weblog-env.Dockerfile#L6).

Let me save you a click (the link is here for context):
````dockerfile
ENV DD_TAGS='key1:val1, key2 : val2 '
````

## Investigation
I found this [RFC from 2021](https://docs.google.com/document/d/1LKOhM59ryAgdJNRKPgy-Id-wgCMpdMaJMMD9aLzQETU) to support space separation in `DD_TAGS`.

Our implementation does not follow the recommend solution of this RFC and end up mixing spaces and commas. The result of our algorithm is:
![Screenshot 2023-12-21 at 17 09 22](https://github.com/DataDog/dd-trace-cpp/assets/204994/6296ae3f-3026-4211-851b-6d097aa20047)

While it should be as follow according to the RFC:
````cpp
const std::vector<StringView> tags {
   {"key1:val1"},
   {"key2 : val2"}
};
````

**Comment by dgoffredo** [comment]
Yeah, I implemented the wrong algorithm.

Prior art in dd-opentracing-cpp:

- https://github.com/DataDog/dd-opentracing-cpp/blob/d07478e1bdecf3ea4f2d64c947e1aecad2c2cf40/doc/configuration.md?plain=1#L203
- https://github.com/DataDog/dd-opentracing-cpp/blob/d07478e1bdecf3ea4f2d64c947e1aecad2c2cf40/src/tracer_options.cpp#L215
- https://github.com/DataDog/dd-opentracing-cpp/blob/d07478e1bdecf3ea4f2d64c947e1aecad2c2cf40/src/tracer_options.cpp#L26
- https://github.com/DataDog/dd-opentracing-cpp/blob/d07478e1bdecf3ea4f2d64c947e1aecad2c2cf40/test/tracer_options_test.cpp#L196-L202

Not easy to see how it handles whitespace. I think it just considers it part of the tag.

I don't remember why I chose the unspecified "hybrid" approach.

Do you think we should follow the RFC? Perhaps it's best to do a survey of the other tracers. There's no relevant test in our internal parametric system tests.

**Comment by dmehala** [comment]
> Yeah, I implemented the wrong algorithm.

You implemented based on what you had back then. 

 > Do you think we should follow the RFC? Perhaps it's best to do a survey of the other tracers. There's no relevant test in our internal parametric system tests.

I did not find a system tests to ensure all tracers follow this RFC, but some of them are able to correctly interpret `DD_TAGS='key1:val1, key2 : val2 '` because they pass [this test](https://github.com/DataDog/system-tests/blob/ef8f886a16d3624d35f56302b5f0c38959d5c6e5/tests/test_semantic_conventions.py#L302-L316)

Upon investigation, at least 4 tracers (Python, Go, Ruby and Java) are following this RFC. I didn't find data for .NET, NodeJS and PHP.

IMO it's better to follow the RFC rather than crash the user application when spaces and commas are mixed.

**Comment by dgoffredo** [comment]
It's not a crash, it's a failure to start due to an invalid configuration:
```
2024/01/10 17:36:50 [notice] 38#38: signal process started
Sending the reload signal to nginx took 0.13857 seconds.
[6305.408870528, "service_log", {"service": "nginx", "payload": "2024/01/10 17:36:50 [error] 44#44: Failed to construct tracer: [error code 24] Unable to parse DD_TAGS environment variable: Unable to parse a key/value from the tag text \"key2\" because it does not contain the separator character \":\".  Error occurred in list of tags \"key1:val1, key2 : val2 \"."}]
Consuming docker compose top PIDs took 0.016283 seconds.
[6305.509158606, "service_log", {"service": "nginx", "payload": "2024/01/10 17:36:50 [alert] 1#1: worker process 44 exited with fatal code 2 and cannot be respawned"}]
Consuming docker compose top PIDs took 0.021696 seconds.
```
Pedantic, sure, but it makes me feel better.

Let's fix the implementation when we get the time.
